---
name: Deploy VMS Assembly

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
jobs:
  # deploy:
  Deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact
    # with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Innovation account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # yamllint disable-line rule:line-length
          role-to-assume: arn:aws:iam::272435851616:role/vms-assembly-Role-Q6LP1AD26VER
          aws-region: ap-southeast-2

      - name: Deploy the awesome app!
        run: |
          make deploy
