---
name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          make install-deps
      - name: Analysing the code with yamllint
        run: |
          make lint-yaml
